//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevHubDBEntities : DbContext
    {
        public DevHubDBEntities()
            : base("name=DevHubDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountConfirmation> AccountConfirmations { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<DevPost> DevPosts { get; set; }
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
        public virtual DbSet<Profession> Professions { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<SocialLink> SocialLinks { get; set; }
    }
}
