//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discussion
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentedOn { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual DevPost DevPost { get; set; }
    }
}
