//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Profile
    {
        public const string defaultImage = "~/Content/img/default.jpg";

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.SocialLinks = new HashSet<SocialLink>();
        }
    
        public System.Guid AccountId { get; set; }
        public Nullable<System.Guid> ProfessionId { get; set; }

        public string Website { get; set; }
        public string Address { get; set; }
        public string Skills { get; set; }
        public string GitHubUsername { get; set; }
        public string Bio { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Profession Profession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocialLink> SocialLinks { get; set; }
    }
}
